#include <stdio.h>
#include "c/include/kokoro.h"

int main() {
    kokoro_t* kokoro = kokoro_init(
        "kokoro-v1.0.onnx",
        "voices-v1.0-c.bin",
        NULL, NULL
    );
    
    if (!kokoro) {
        fprintf(stderr, "Failed to initialize\n");
        return 1;
    }
    
    printf("Initialized successfully\n");
    
    kokoro_audio_t audio = {0};
    const char* text = "Hello. This audio generated by kokoro!";
    
    printf("Generating audio for: %s\n", text);
    
    kokoro_error_t err = kokoro_create(
        kokoro, text, "af_sarah", 1.0f, "en-us", &audio
    );
    
    if (err != KOKORO_SUCCESS) {
        fprintf(stderr, "Failed to create audio: %d\n", err);
        kokoro_free(kokoro);
        return 1;
    }
    
    printf("Generated %zu samples at %d Hz\n", audio.num_samples, audio.sample_rate);
    printf("Duration: %.2f seconds\n", (float)audio.num_samples / audio.sample_rate);
    
    kokoro_audio_free(&audio);
    kokoro_free(kokoro);
    
    return 0;
}
