#include <stdio.h>
#include "c/include/kokoro.h"

int main() {
    kokoro_t* kokoro = kokoro_init(
        "kokoro-v1.0.onnx",
        "voices-v1.0-c.bin",
        NULL, NULL
    );
    
    if (!kokoro) {
        fprintf(stderr, "Failed to initialize\n");
        return 1;
    }
    
    char* phonemes = NULL;
    const char* text = "Hello. This audio generated by kokoro!";
    
    kokoro_error_t err = kokoro_text_to_phonemes(kokoro, text, "en-us", &phonemes);
    if (err != KOKORO_SUCCESS) {
        fprintf(stderr, "Failed to get phonemes: %d\n", err);
        kokoro_free(kokoro);
        return 1;
    }
    
    printf("Text: %s\n", text);
    printf("Phonemes: %s\n", phonemes);
    printf("Phoneme length: %zu\n", strlen(phonemes));
    
    free(phonemes);
    kokoro_free(kokoro);
    
    return 0;
}
