/**
 * Argument Parsing Utilities for Kokoro TTS C Programs
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include "argparse.h"

void print_example_help(const char* program_name) {
    printf("Kokoro TTS Example - Text-to-Speech Synthesis\n\n");
    printf("Usage: %s [OPTIONS] -m MODEL -v VOICES -o OUTPUT\n", program_name);
    printf("   or: %s MODEL VOICES OUTPUT [VOICE] [TEXT] [SPEED]\n\n", program_name);
    
    printf("Generate speech from text using Kokoro TTS.\n\n");
    
    printf("Required Options:\n");
    printf("  -m, --model MODEL       Path to ONNX model file\n");
    printf("  -v, --voices VOICES     Path to voices binary file (C format)\n");
    printf("  -o, --output OUTPUT     Path to output WAV file\n\n");
    
    printf("Optional Options:\n");
    printf("  -V, --voice VOICE       Voice name (default: af_sarah)\n");
    printf("  -t, --text TEXT         Text to synthesize (default: greeting message)\n");
    printf("  -s, --speed SPEED       Speech speed 0.5-2.0 (default: 1.0)\n");
    printf("  -l, --lang LANG         Language code (default: en-us)\n");
    printf("  -h, --help              Show this help message\n\n");
    
    printf("Examples:\n");
    printf("  # Using flags (recommended)\n");
    printf("  %s -m model.onnx -v voices.bin -o output.wav\n", program_name);
    printf("  %s -m model.onnx -v voices.bin -o output.wav -V af_sarah -t \"Hello!\" -s 1.2\n\n", program_name);
    
    printf("  # Using positional arguments (backward compatible)\n");
    printf("  %s model.onnx voices.bin output.wav\n", program_name);
    printf("  %s model.onnx voices.bin output.wav af_sarah \"Hello!\" 1.2\n\n", program_name);
    
    printf("  # With resources directory\n");
    printf("  %s -m resources/kokoro-v1.0.onnx -v resources/voices-v1.0-c.bin -o output.wav\n\n", program_name);
    
    printf("Available Voices:\n");
    printf("  af_sarah, af_bella, af_sky, af_jessica, am_adam, am_michael, and more\n\n");
    
    printf("Notes:\n");
    printf("  - The voices file must be in C binary format (voices-v1.0-c.bin)\n");
    printf("  - Use: python3 scripts/convert_voices.py to convert from Python format\n");
    printf("  - Speed range: 0.5 (slow) to 2.0 (fast), 1.0 is normal\n");
}

void print_audiobook_help(const char* program_name) {
    printf("Kokoro Audiobook Generator\n\n");
    printf("Usage: %s [OPTIONS] -m MODEL -v VOICES -i INPUT -o OUTPUT\n", program_name);
    printf("   or: %s MODEL VOICES INPUT OUTPUT [VOICE] [LANG] [SPEED]\n\n", program_name);
    
    printf("Generate audiobook from text file with natural pauses.\n\n");
    
    printf("Required Options:\n");
    printf("  -m, --model MODEL       Path to ONNX model file\n");
    printf("  -v, --voices VOICES     Path to voices binary file (C format)\n");
    printf("  -i, --input INPUT       Input text file\n");
    printf("  -o, --output OUTPUT     Output WAV file\n\n");
    
    printf("Optional Options:\n");
    printf("  -V, --voice VOICE       Voice name (default: af_sarah)\n");
    printf("  -l, --lang LANG         Language code (default: en-us)\n");
    printf("  -s, --speed SPEED       Speech speed 0.5-2.0 (default: 1.0)\n");
    printf("  -h, --help              Show this help message\n\n");
    
    printf("Text File Features:\n");
    printf("  - Automatic pauses at: . ! ? (500ms), , (250ms), ; : (350ms)\n");
    printf("  - Paragraph breaks: empty lines (800ms pause)\n");
    printf("  - Custom pauses: [PAUSE:500] for 500ms pause\n\n");
    
    printf("Examples:\n");
    printf("  # Using flags (recommended)\n");
    printf("  %s -m model.onnx -v voices.bin -i story.txt -o audiobook.wav\n", program_name);
    printf("  %s -m model.onnx -v voices.bin -i story.txt -o audiobook.wav -V af_bella -s 1.1\n\n", program_name);
    
    printf("  # Using positional arguments (backward compatible)\n");
    printf("  %s model.onnx voices.bin story.txt audiobook.wav\n", program_name);
    printf("  %s model.onnx voices.bin story.txt audiobook.wav af_sarah en-us 1.0\n\n", program_name);
}

int parse_example_args(
    int argc,
    char** argv,
    const char** model_path,
    const char** voices_path,
    const char** output_path,
    const char** voice_name,
    const char** text,
    float* speed,
    const char** lang
) {
    /* Set defaults */
    *model_path = NULL;
    *voices_path = NULL;
    *output_path = NULL;
    *voice_name = "af_sarah";
    *text = "Hello, this audio was generated by Kokoro in C";
    *speed = 1.0f;
    *lang = "en-us";
    
    /* Check for positional arguments first (backward compatibility) */
    if (argc >= 4 && argv[1][0] != '-') {
        /* Positional argument mode */
        *model_path = argv[1];
        *voices_path = argv[2];
        *output_path = argv[3];
        if (argc > 4) *voice_name = argv[4];
        if (argc > 5) *text = argv[5];
        if (argc > 6) {
            *speed = atof(argv[6]);
            if (*speed < 0.5f || *speed > 2.0f) {
                fprintf(stderr, "Warning: Speed %.2f is out of recommended range (0.5-2.0), clamping...\n", *speed);
                if (*speed < 0.5f) *speed = 0.5f;
                if (*speed > 2.0f) *speed = 2.0f;
            }
        }
        return 0;
    }
    
    /* Flag-based argument parsing */
    static struct option long_options[] = {
        {"model",   required_argument, 0, 'm'},
        {"voices",  required_argument, 0, 'v'},
        {"output",  required_argument, 0, 'o'},
        {"voice",   required_argument, 0, 'V'},
        {"text",    required_argument, 0, 't'},
        {"speed",   required_argument, 0, 's'},
        {"lang",    required_argument, 0, 'l'},
        {"help",    no_argument,       0, 'h'},
        {0, 0, 0, 0}
    };
    
    int opt;
    int option_index = 0;
    
    while ((opt = getopt_long(argc, argv, "m:v:o:V:t:s:l:h", long_options, &option_index)) != -1) {
        switch (opt) {
            case 'm':
                *model_path = optarg;
                break;
            case 'v':
                *voices_path = optarg;
                break;
            case 'o':
                *output_path = optarg;
                break;
            case 'V':
                *voice_name = optarg;
                break;
            case 't':
                *text = optarg;
                break;
            case 's':
                *speed = atof(optarg);
                if (*speed < 0.5f || *speed > 2.0f) {
                    fprintf(stderr, "Error: Speed must be between 0.5 and 2.0\n");
                    return -1;
                }
                break;
            case 'l':
                *lang = optarg;
                break;
            case 'h':
                print_example_help(argv[0]);
                return 1;
            default:
                print_example_help(argv[0]);
                return -1;
        }
    }
    
    /* Validate required arguments */
    if (!*model_path || !*voices_path || !*output_path) {
        fprintf(stderr, "Error: Missing required arguments\n\n");
        print_example_help(argv[0]);
        return -1;
    }
    
    return 0;
}

int parse_audiobook_args(
    int argc,
    char** argv,
    const char** model_path,
    const char** voices_path,
    const char** input_path,
    const char** output_path,
    const char** voice_name,
    const char** lang,
    float* speed
) {
    /* Set defaults */
    *model_path = NULL;
    *voices_path = NULL;
    *input_path = NULL;
    *output_path = NULL;
    *voice_name = "af_sarah";
    *lang = "en-us";
    *speed = 1.0f;
    
    /* Check for positional arguments first (backward compatibility) */
    if (argc >= 5 && argv[1][0] != '-') {
        /* Positional argument mode */
        *model_path = argv[1];
        *voices_path = argv[2];
        *input_path = argv[3];
        *output_path = argv[4];
        if (argc > 5) *voice_name = argv[5];
        if (argc > 6) *lang = argv[6];
        if (argc > 7) {
            *speed = atof(argv[7]);
            if (*speed < 0.5f || *speed > 2.0f) {
                fprintf(stderr, "Error: Speed must be between 0.5 and 2.0\n");
                return -1;
            }
        }
        return 0;
    }
    
    /* Flag-based argument parsing */
    static struct option long_options[] = {
        {"model",   required_argument, 0, 'm'},
        {"voices",  required_argument, 0, 'v'},
        {"input",   required_argument, 0, 'i'},
        {"output",  required_argument, 0, 'o'},
        {"voice",   required_argument, 0, 'V'},
        {"lang",    required_argument, 0, 'l'},
        {"speed",   required_argument, 0, 's'},
        {"help",    no_argument,       0, 'h'},
        {0, 0, 0, 0}
    };
    
    int opt;
    int option_index = 0;
    
    while ((opt = getopt_long(argc, argv, "m:v:i:o:V:l:s:h", long_options, &option_index)) != -1) {
        switch (opt) {
            case 'm':
                *model_path = optarg;
                break;
            case 'v':
                *voices_path = optarg;
                break;
            case 'i':
                *input_path = optarg;
                break;
            case 'o':
                *output_path = optarg;
                break;
            case 'V':
                *voice_name = optarg;
                break;
            case 'l':
                *lang = optarg;
                break;
            case 's':
                *speed = atof(optarg);
                if (*speed < 0.5f || *speed > 2.0f) {
                    fprintf(stderr, "Error: Speed must be between 0.5 and 2.0\n");
                    return -1;
                }
                break;
            case 'h':
                print_audiobook_help(argv[0]);
                return 1;
            default:
                print_audiobook_help(argv[0]);
                return -1;
        }
    }
    
    /* Validate required arguments */
    if (!*model_path || !*voices_path || !*input_path || !*output_path) {
        fprintf(stderr, "Error: Missing required arguments\n\n");
        print_audiobook_help(argv[0]);
        return -1;
    }
    
    return 0;
}
